!!!!!!!  SCRIPT DEVELOPED BY Dr. ADITYA KAPOOR !!!!!!!!!!!!!!!
!!!!!!! RESEARCH ASSOCIATE, ICED, IIT ROORKEE  !!!!!!!!!!!!!!!
    
    
PROGRAM MAIN

INTEGER:: N_OBS,N_TIMES,N_NODES,N_ELEMENTS
INTEGER:: N_REGIONS
CHARACTER(LEN=40)::OBS_NAME(100)
REAL::OBS_P(100,100),OBS_C(100,100),OBS_SAT(100,100)
REAL::OBS_X(100),OBS_Y(100)
REAL::COMP_P(100,100),COMP_C(100,100),COMP_SAT(100,100)
INTEGER::TIME_STEP(100)
REAL::TIMES(100)
REAL::SWRES_NREG(100),AA_NREG(100),VN_NREG(100)
REAL::KMAX_NREG(100),KMIN_NREG(100),POROSITY_NREG(100)
REAL::ANGLE1_NREG(100),ALMAX_NREG(100),ALMIN_NREG(100),ATMAX_NREG(100),ATMIN_NREG(100)
INTEGER::NODE_NUMBER(200000),NODE_REGION(200000)
INTEGER::ELEMENT_NUMBER(200000),ELEMENT_REGION(200000)
REAL::NODE_X(200000),NODE_Y(200000),NODE_Z(200000)
COMMON/PARAMETERS_NREG/SWRES_NREG,AA_NREG,VN_NREG


WRITE(*,*) 'ENSURE THAT OBC FORMAT HAS BEEN ADOPTED WHILE PLACING OBSERVATION POINTS'
WRITE(*,*) ''
WRITE(*,*) 'DEFINE CUSTOM SCHEDULE AND JUST ONE OBSERVATION TIME AS 0' 
WRITE(*,*) 'THIS WILL LEAD TO PRINTING OF RESULT AT 0 TIME STEP AND THE LAST TIME STEP'
WRITE(*,*) ''
!N_OBS: I LOOP
!TIMES: K LOOP
!N_REGIONS (N_REG IN SUTRA DOCUMENTATION): N LOOP

OPEN(UNIT=101, FILE='INPUT_N.txt', STATUS='OLD')
READ(101,*) N_OBS,N_TIMES,N_NODES,N_ELEMENTS
WRITE(*,*) N_OBS,N_TIMES,N_NODES,N_ELEMENTS
CLOSE(101)

!!!READ VAN GENUCHTEN PARAMETERS, PERMEABILITIES AND POROSITIES
OPEN(UNIT=102, FILE='INPUT_REGION.txt', STATUS='OLD')
READ(102,*) N_REGIONS
    WRITE(*,*) 'NUMBER OF REGIONS DEFINED=',N_REGIONS
    WRITE(*,*) 'REGION WISE UNSAT PARAMETERS'
    DO N=1,N_REGIONS,1
    READ(102,*) SWRES_NREG(N),AA_NREG(N),VN_NREG(N),KMAX_NREG(N),KMIN_NREG(N),POROSITY_NREG(N), &
                ANGLE1_NREG(N),ALMAX_NREG(N),ALMIN_NREG(N),ATMAX_NREG(N),ATMIN_NREG(N)
    WRITE(*,*) N,SWRES_NREG(N),AA_NREG(N),VN_NREG(N),KMAX_NREG(N),KMIN_NREG(N),POROSITY_NREG(N), &
                ANGLE1_NREG(N),ALMAX_NREG(N),ALMIN_NREG(N),ATMAX_NREG(N),ATMIN_NREG(N)
    END DO
    WRITE(*,*) ''
CLOSE(102)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! DATA WRITING: NEEDED JUST IN THE BEGINNING OF A NEW MODEL

!!! BE CAREFUL WHILE WRITING AS ALL THE COMPONENTS REQUIRED IN A FILE MUST BE WRITTEN

!OPEN(UNIT=101, FILE='1_NODE_RAW.txt', STATUS='UNKNOWN',ACTION='READ')
!OPEN(UNIT=102, FILE='1_NODE_INFO.txt', STATUS='UNKNOWN',ACTION='WRITE')
!DO I=1,N_NODES,1
!READ(101,*) NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I)
!WRITE(102,*) NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I)
!END DO
!CLOSE(102)
!CLOSE(101)

!OPEN(UNIT=101, FILE='1_ELEMENT_RAW.txt', STATUS='UNKNOWN',ACTION='READ')
!OPEN(UNIT=102, FILE='1_ELEMENT_INFO.txt', STATUS='UNKNOWN',ACTION='WRITE')
!DO I=1,N_ELEMENTS,1
!READ(101,*) ELEMENT_NUMBER(I),ELEMENT_REGION(I)
!WRITE(102,*) ELEMENT_NUMBER(I),ELEMENT_REGION(I)
!END DO
!CLOSE(102)
!CLOSE(101)
!!! DATA WRITING ENDS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


OPEN(UNIT=102, FILE='1_NODE_INFO.txt', STATUS='UNKNOWN',ACTION='READ')
DO I=1,N_NODES,1
READ(102,*) NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I)
!WRITE(*,*) NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I)
END DO
CLOSE(102)

OPEN(UNIT=102, FILE='1_ELEMENT_INFO.txt', STATUS='UNKNOWN',ACTION='READ')
DO I=1,N_ELEMENTS,1
READ(102,*) ELEMENT_NUMBER(I),ELEMENT_REGION(I)
!WRITE(*,*) ELEMENT_NUMBER(I),ELEMENT_REGION(I)
END DO
CLOSE(102)

!!!USED @INSERT 51 '1_NODE_INP.txt' FOR DATASET:14B
OPEN(UNIT=102, FILE='1_NODE_INP.txt', STATUS='UNKNOWN',ACTION='WRITE')
DO I=1,N_NODES,1
WRITE(102,'(I8,I4,3F12.4,3X,F6.3)') NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I),POROSITY_NREG(NODE_REGION(I))
!WRITE(*,*) NODE_NUMBER(I),NODE_REGION(I),NODE_X(I),NODE_Y(I),NODE_Z(I)
END DO
CLOSE(102)

!!!USED @INSERT 52 '1_ELEMENT_INP.txt' FOR DATASET:14B
OPEN(UNIT=102, FILE='1_ELEMENT_INP.txt', STATUS='UNKNOWN',ACTION='WRITE')
DO I=1,N_ELEMENTS,1
WRITE(102,'(I8,I4,2(1X,1PE15.7),5(1X,1PE15.7))') ELEMENT_NUMBER(I),ELEMENT_REGION(I), &
        KMAX_NREG(ELEMENT_REGION(I)),KMIN_NREG(ELEMENT_REGION(I)), &
        ANGLE1_NREG(ELEMENT_REGION(I)),ALMAX_NREG(ELEMENT_REGION(I)),ALMIN_NREG(ELEMENT_REGION(I)), &
        ATMAX_NREG(ELEMENT_REGION(I)),ATMIN_NREG(ELEMENT_REGION(I))
END DO
CLOSE(102)

OPEN(UNIT=999, FILE = 'COMPUTED.txt',STATUS='UNKNOWN')
    CALL SUTRA_MAIN()
CLOSE(999)

WRITE(*,*) 'SUTRA CALLED SUCCESSFULLY'

OPEN(UNIT=1000, FILE = 'COMPUTED.txt',STATUS='OLD')
    DO K=1,N_TIMES,1
    DO I=N_OBS,1,-1
        READ(1000,*) OBS_NAME(I),OBS_X(I),OBS_Y(I),TIME_STEP(K),TIMES(K),COMP_P(I,K),COMP_C(I,K),COMP_SAT(I,K)
        WRITE (*,*) 'I=',I,'K=',K,OBS_NAME(I),OBS_X(I),OBS_Y(I),TIME_STEP(K),TIMES(K),K,COMP_P(I,K),COMP_C(I,K),COMP_SAT(I,K)
    END DO
    END DO
CLOSE(1000)

PAUSE
END PROGRAM MAIN